### ISSUE TITLE
MapProperties from Dto

### ISSUE THREAD

**Issue by Mrsevic** [jeuxjeux20/EntityFrameworkRocket#2]
Hello, I am not able to see any refactoring suggestion whilst hovering the icon or using the Ctrl plus dot combination in the code. 

There is a loop for some time and afterwards I simply do not see the suggestion in the list like in your gif.

**Comment by DynamicField** [comment]
Can you please send some sample code to reproduce the issue? Thanks!

**Comment by Mrsevic** [comment]
False alarm, I was trying an unsupported scenario where you would be able to the automapping in the constructor itself.
